// ===================================
// بيانات عقود الاعتماد الأكاديمي
// إجمالي العقود: 445
// آخر تحديث: 2024-11-29
// ===================================

const contractsData = [
  // الجامعة الإسلامية - 3 عقود
  {
    id: "001",
    program: "الاقتصاد",
    college: "كلية الأنظمة والاقتصاد",
    university: "الجامعة الإسلامية",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الإنسانية والتربوية",
    status: "تحت الإجراء",
    progress: "40%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "01/23/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "تم التسليم متأخر",
    updateDocDate: "05/15/25",
    updateDocConditions: "تم التسليم متأخر",
    verifyVisitSchedule: "05/15/25",
    verifyScheduleConditions: "تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "01/25/26",
    reviewerScheduleConditions: "تم جدولة الزيارة - متأخر",
    startDate: "03/07/24",
    endDate: "03/06/25"
  },
  {
    id: "002",
    program: "الإعلام والاتصال",
    college: "كلية اللغة العربية والدراسات الإنسانية",
    university: "الجامعة الإسلامية",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الإنسانية والتربوية",
    status: "تحت الإجراء",
    progress: "40%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "01/23/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "تم التسليم متأخر",
    updateDocDate: "08/31/25",
    updateDocConditions: "تم التسليم متأخر",
    verifyVisitSchedule: "09/04/25",
    verifyScheduleConditions: "تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "02/01/26",
    reviewerScheduleConditions: "تم جدولة الزيارة - متأخر",
    startDate: "03/07/24",
    endDate: "03/06/25"
  },
  {
    id: "003",
    program: "أصول التربية الإسلامية",
    college: "كلية اللغة العربية والدراسات الإنسانية",
    university: "الجامعة الإسلامية",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الإنسانية والتربوية",
    status: "تحت الإجراء",
    progress: "40%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "01/23/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "تم التسليم متأخر",
    updateDocDate: "04/13/25",
    updateDocConditions: "تم التسليم متأخر",
    verifyVisitSchedule: "04/16/25",
    verifyScheduleConditions: "تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "11/30/25",
    reviewerScheduleConditions: "تم جدولة الزيارة - متأخر",
    startDate: "03/07/24",
    endDate: "03/06/25"
  },
  
  // جامعة الإمام عبد الرحمن بن فيصل - عقود متنوعة
  {
    id: "004",
    program: "العلوم في إدارة هندسة التشييد",
    college: "كلية العمارة والتخطيط",
    university: "جامعة الإمام عبد الرحمن بن فيصل",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "5%",
    docReceiveStatus: "لم يتم التسليم",
    docReceiveDate: "",
    docReceiveConditions: "لم يتم التسليم",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "",
    verifyVisitSchedule: "",
    verifyScheduleConditions: "",
    reviewerVisitSchedule: "",
    reviewerScheduleConditions: "",
    startDate: "06/20/24",
    endDate: "01/31/26"
  },
  {
    id: "005",
    program: "التصميم الصناعي",
    college: "كلية التصاميم",
    university: "جامعة الإمام عبد الرحمن بن فيصل",
    degree: "بكالوريوس",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "5%",
    docReceiveStatus: "لم يتم التسليم",
    docReceiveDate: "",
    docReceiveConditions: "لم يتم التسليم",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "",
    verifyVisitSchedule: "",
    verifyScheduleConditions: "",
    reviewerVisitSchedule: "",
    reviewerScheduleConditions: "",
    startDate: "06/20/24",
    endDate: "01/31/26"
  },
  {
    id: "006",
    program: "العلوم في الإدارة الهندسية",
    college: "كلية الهندسة",
    university: "جامعة الإمام عبد الرحمن بن فيصل",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "5%",
    docReceiveStatus: "لم يتم التسليم",
    docReceiveDate: "",
    docReceiveConditions: "لم يتم التسليم",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "",
    verifyVisitSchedule: "",
    verifyScheduleConditions: "",
    reviewerVisitSchedule: "",
    reviewerScheduleConditions: "",
    startDate: "06/20/24",
    endDate: "01/31/26"
  },
  {
    id: "007",
    program: "العلوم في الهندسة البيئية",
    college: "كلية الهندسة",
    university: "جامعة الإمام عبد الرحمن بن فيصل",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "5%",
    docReceiveStatus: "لم يتم التسليم",
    docReceiveDate: "",
    docReceiveConditions: "لم يتم التسليم",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "",
    verifyVisitSchedule: "",
    verifyScheduleConditions: "",
    reviewerVisitSchedule: "",
    reviewerScheduleConditions: "",
    startDate: "06/20/24",
    endDate: "01/31/26"
  },
  {
    id: "008",
    program: "العلوم في نظم المعلومات وتحليل البيانات",
    college: "كلية علوم الحاسب وتقنية المعلومات",
    university: "جامعة الإمام عبد الرحمن بن فيصل",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "5%",
    docReceiveStatus: "لم يتم التسليم",
    docReceiveDate: "",
    docReceiveConditions: "لم يتم التسليم",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "",
    verifyVisitSchedule: "",
    verifyScheduleConditions: "",
    reviewerVisitSchedule: "",
    reviewerScheduleConditions: "",
    startDate: "06/20/24",
    endDate: "01/31/26"
  },
  {
    id: "009",
    program: "العمارة",
    college: "كلية العمارة والتخطيط",
    university: "جامعة الإمام عبد الرحمن بن فيصل",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "5%",
    docReceiveStatus: "لم يتم التسليم",
    docReceiveDate: "",
    docReceiveConditions: "لم يتم التسليم",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "",
    verifyVisitSchedule: "",
    verifyScheduleConditions: "",
    reviewerVisitSchedule: "",
    reviewerScheduleConditions: "",
    startDate: "06/20/24",
    endDate: "01/31/26"
  },
  {
    id: "010",
    program: "العلوم في جودة الرعاية الصحية وسلامة المرضى",
    college: "كلية الصحة العامة",
    university: "جامعة الإمام عبد الرحمن بن فيصل",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الصحية",
    status: "تحت الإجراء",
    progress: "40%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "01/15/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "تم التسليم متأخر",
    updateDocDate: "06/05/25",
    updateDocConditions: "تم التسليم متأخر",
    verifyVisitSchedule: "04/28/25",
    verifyScheduleConditions: "لم تتم جدولة الزيارة",
    reviewerVisitSchedule: "",
    reviewerScheduleConditions: "",
    startDate: "06/20/24",
    endDate: "01/31/26"
  },
  
  // جامعة الملك سعود - عقود متنوعة
  {
    id: "011",
    program: "التطوير العقاري",
    college: "كلية العمارة والتخطيط",
    university: "جامعة الملك سعود",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "30%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "09/25/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "- بدون تسليم وثائق محدثة - تم جدولة الزيارة - متأخر",
    verifyVisitSchedule: "12/18/25",
    verifyScheduleConditions: "- بدون تسليم وثائق محدثة - تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "04/05/26",
    reviewerScheduleConditions: "- بدون تسليم وثائق محدثة - تم جدولة الزيارة - متأخر",
    startDate: "03/04/25",
    endDate: "03/03/26"
  },
  {
    id: "012",
    program: "الطب والجراحة",
    college: "كلية الطب البشري",
    university: "جامعة الملك سعود",
    degree: "بكالوريوس",
    department: "إدارة برامج العلوم الصحية",
    status: "تحت الإجراء",
    progress: "40%",
    docReceiveStatus: "تم التسليم",
    docReceiveDate: "04/21/25",
    docReceiveConditions: "تم التسليم",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "- بدون تسليم وثائق محدثة - تم جدولة الزيارة - متأخر",
    verifyVisitSchedule: "09/07/25",
    verifyScheduleConditions: "- بدون تسليم وثائق محدثة - تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "12/01/25",
    reviewerScheduleConditions: "- بدون تسليم وثائق محدثة - تم جدولة الزيارة - متأخر",
    startDate: "02/10/25",
    endDate: "02/09/26"
  },
  
  // جامعة الملك عبد العزيز
  {
    id: "013",
    program: "هندسة الطيران",
    college: "كلية الهندسة",
    university: "جامعة الملك عبد العزيز",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "5%",
    docReceiveStatus: "لم يتم التسليم",
    docReceiveDate: "",
    docReceiveConditions: "لم يتم التسليم",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "",
    verifyVisitSchedule: "",
    verifyScheduleConditions: "",
    reviewerVisitSchedule: "",
    reviewerScheduleConditions: "",
    startDate: "04/13/23",
    endDate: "06/30/26"
  },
  {
    id: "014",
    program: "الهندسة الصناعية",
    college: "كلية الهندسة",
    university: "جامعة الملك عبد العزيز",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "5%",
    docReceiveStatus: "لم يتم التسليم",
    docReceiveDate: "",
    docReceiveConditions: "لم يتم التسليم",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "",
    verifyVisitSchedule: "",
    verifyScheduleConditions: "",
    reviewerVisitSchedule: "",
    reviewerScheduleConditions: "",
    startDate: "04/13/23",
    endDate: "06/30/26"
  },
  {
    id: "015",
    program: "الإدارة الهندسية",
    college: "كلية الهندسة",
    university: "جامعة الملك عبد العزيز",
    degree: "ماجستير",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "40%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "09/07/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "تم التسليم متأخر",
    updateDocDate: "11/02/25",
    updateDocConditions: "تم التسليم متأخر",
    verifyVisitSchedule: "11/05/25",
    verifyScheduleConditions: "تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "01/25/26",
    reviewerScheduleConditions: "تم جدولة الزيارة - متأخر",
    startDate: "04/13/23",
    endDate: "06/30/26"
  },
  
  // جامعة القصيم
  {
    id: "016",
    program: "هندسة الحاسب",
    college: "كلية الحاسب",
    university: "جامعة القصيم",
    degree: "بكالوريوس",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "40%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "06/16/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "تم التسليم متأخر",
    updateDocDate: "09/09/25",
    updateDocConditions: "تم التسليم متأخر",
    verifyVisitSchedule: "09/11/25",
    verifyScheduleConditions: "تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "04/05/26",
    reviewerScheduleConditions: "تم جدولة الزيارة - متأخر",
    startDate: "10/09/24",
    endDate: "10/08/25"
  },
  {
    id: "017",
    program: "تقنية المعلومات",
    college: "كلية الحاسب",
    university: "جامعة القصيم",
    degree: "بكالوريوس",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "40%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "06/16/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "تم التسليم متأخر",
    updateDocDate: "09/09/25",
    updateDocConditions: "تم التسليم متأخر",
    verifyVisitSchedule: "09/11/25",
    verifyScheduleConditions: "تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "04/05/26",
    reviewerScheduleConditions: "تم جدولة الزيارة - متأخر",
    startDate: "10/09/24",
    endDate: "10/08/25"
  },
  {
    id: "018",
    program: "علوم الحاسب",
    college: "كلية الحاسب",
    university: "جامعة القصيم",
    degree: "بكالوريوس",
    department: "إدارة برامج العلوم الهندسية وعلوم الحاسب",
    status: "تحت الإجراء",
    progress: "40%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "06/16/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "تم التسليم متأخر",
    updateDocDate: "09/09/25",
    updateDocConditions: "تم التسليم متأخر",
    verifyVisitSchedule: "09/11/25",
    verifyScheduleConditions: "تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "04/05/26",
    reviewerScheduleConditions: "تم جدولة الزيارة - متأخر",
    startDate: "10/09/24",
    endDate: "10/08/25"
  },
  {
    id: "019",
    program: "الشريعة",
    college: "كلية الشريعة",
    university: "جامعة القصيم",
    degree: "بكالوريوس",
    department: "إدارة برامج العلوم الإسلامية والعربية",
    status: "تحت الإجراء",
    progress: "40%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "07/27/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "تم التسليم متأخر",
    updateDocDate: "07/27/25",
    updateDocConditions: "تم التسليم متأخر",
    verifyVisitSchedule: "09/08/25",
    verifyScheduleConditions: "تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "11/30/25",
    reviewerScheduleConditions: "تم جدولة الزيارة - متأخر",
    startDate: "10/09/24",
    endDate: "10/08/25"
  },
  {
    id: "020",
    program: "دكتور صيدلة",
    college: "كلية الصيدلة",
    university: "جامعة القصيم",
    degree: "بكالوريوس",
    department: "إدارة برامج العلوم الصحية",
    status: "تحت الإجراء",
    progress: "30%",
    docReceiveStatus: "تم التسليم متأخر",
    docReceiveDate: "10/08/25",
    docReceiveConditions: "تم التسليم متأخر",
    updateDocStatus: "لم يتم التسليم",
    updateDocDate: "",
    updateDocConditions: "- بدون تسليم وثائق محدثة - تم جدولة الزيارة - متأخر",
    verifyVisitSchedule: "12/10/25",
    verifyScheduleConditions: "- بدون تسليم وثائق محدثة - تم جدولة الزيارة - متأخر",
    reviewerVisitSchedule: "01/25/26",
    reviewerScheduleConditions: "- بدون تسليم وثائق محدثة - تم جدولة الزيارة - متأخر",
    startDate: "10/09/24",
    endDate: "10/08/25"
  }
  
  // ===============================================
  // ملاحظة: هذا ملف نموذجي يحتوي على 20 عقد
  // لإضافة جميع الـ 445 عقد، استخدم نفس البنية
  // ===============================================
  
  // يمكنك نسخ ولصق المزيد من العقود هنا
  // فقط تأكد من:
  // 1. معرف (id) فريد لكل عقد
  // 2. اتباع نفس الهيكل
  // 3. فاصلة بين كل عقد
  // 4. عدم وجود فاصلة بعد آخر عقد
];

// معلومات النظام
const systemInfo = {
  totalContracts: contractsData.length,
  version: "1.0.0",
  lastUpdate: "2024-11-29",
  dataStructure: "v1.0",
  
  // إحصائيات سريعة
  stats: {
    universities: [...new Set(contractsData.map(c => c.university))].length,
    programs: [...new Set(contractsData.map(c => c.program))].length,
    degrees: [...new Set(contractsData.map(c => c.degree))].length,
    departments: [...new Set(contractsData.map(c => c.department))].length
  }
};

// تصدير البيانات
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { contractsData, systemInfo };
}

// سجل في الـ Console
console.log(`%c✓ تم تحميل ${contractsData.length} عقد بنجاح`, 
  'color: #10b981; font-weight: bold; font-size: 14px;');
console.log(`%cالجامعات: ${systemInfo.stats.universities} | البرامج: ${systemInfo.stats.programs}`,
  'color: #3b82f6; font-size: 12px;');